apiVersion: apps/v1
kind: Deployment
metadata:
  name: internal-tool
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: internal-tool
  template:
    metadata:
      labels:
        app: internal-tool
    spec:
      containers:
        - name: internal-tool
          image: nginxdemos/hello:latest
          ports:
            - containerPort: 80
