---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian"

- name: Install web server package
  ansible.builtin.package:
    name: "{{ webserver_package }}"
    state: present
