apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capstone-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/YOUR_FORK.git
    targetRevision: main
    path: labs/lab-15-enterprise-capstone/gitops-repo-capstone-app/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: capstone
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
